---
apiVersion: postgresl.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  description: "Coder DB"
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 10Gi
