---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 3
  description: "Coder DB"
  # affinity:
  #   nodeSelector:
  #     kubernetes.io/arch: arm64
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 50Gi
