apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  chart:
    spec:
      chart: coder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-v2
      version: 2.x.x
  interval: 1m0s
  values: # https://github.com/coder/coder/tree/main/helm/coder
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: cluster-app
              key: uri
        - name: CODER_ACCESS_URL
          value: "https://coder.benwoodward.cloud"
      service:
        enable: true
        type: ClusterIP
