apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pixie-operator
  namespace: pl
spec:
  chart:
    spec:
      chart: coder
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coder-v2
      version: 2.x.x
  interval: 1m0s
  # values:
  #   coder:
  #     env:
  #       - name: CODER_ACCESS_URL
  #         value: "https://coder.benwoodward.cloud"
