---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  chart:
    spec:
      chart: proxmox-csi-plugin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-proxmox
      version: 0.3.4
  interval: 1m0s
