---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  type: "oci"
  interval: 1m0s
  url: oci://ghcr.io/sergelogvinov/charts
