---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare
      interval: 12h
  values: {}
