---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare
      interval: 12h
  values:
    cloudflare:
      tunnelId: eb1c8cef-12ae-41fd-9c10-e54e1adb7685
