apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-cloudflare-tunnel
    namespace: cloudflare
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:h54J73+Ivb05+m1NyaHLra9cNcN5WMW1YhgygfDCrKmhXKl2/a6/mqTVQ3qlkdJga18vxcI1tU4TeAMnpfSgTwuQTx7ZyGuvLAqO38LCdNdtfa59CG5tGAeC2AI+FZ4WXJ+E9pKbxoDOMTD+IAS/iMrba7D1ri7zfADthokSANoHWrRiOBORnMXZTs7bDomN0ieQjh0E1V1NSmJO2MMz13LVzwZs1dNO0/cgu5vtqeVTyPhz1NBvrA==,iv:CRmV+7f9IUOEAUVA7Tj9Q+I+WufmY4RihjRutH4EefM=,tag:Qt5LiDdCyADK323++B7wmg==,type:str]
sops:
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcGEyRjZLUzg2elF4Z1k4
            VVpDQnpVRFA5OVNzZEpyZzVhWHREYVFOYUQ4CkFHT2NMY3NOMnFTMVcxWWY2TW1M
            VHg4ellqelIyMnM1dVEvTHBCU3pvS28KLS0tIER0Rm1hd1ZHOEdBY2lwYlBXSWxD
            cXNMSGdpL0hkaHZpZ0oranVzbWptRzAKHfdlhZ3x1gQJFi1FNtTI9o0yvtJpl4ub
            29vjQm0xqDZ3CZAky4VhMgnO6cbliumrfyAomMIcfl9byJwPzpzP8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T22:31:34Z"
    mac: ENC[AES256_GCM,data:I6+AbD0yAgXQzSUIZ7XsYFPaFeoxNdE4VT4dwIs6uJiFRwKCl7J8k3CuqvSvIvws08UkcV70v6M6OQSVMw2Vb6slD8ZxQfpXc3F2ccMGVlwO4xbwkWYvzocsglyoxWrAtWs1F5aiYINFTi9r3iiJMRuU+yyEVIsZMUWLAvGbBnw=,iv:QZ/6J5s86PoxKMFgnlYhdyG0S1+l3TvW0dys5S+pP+4=,tag:tH56R8xZ+oERU1QIof7H2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
