---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeshark
  namespace: kubeshark
spec:
  chart:
    spec:
      chart: kubeshark
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubeshark
      version: 52.8.x
  interval: 1m0s
