apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:YNi0ihMqS70JrTHueAFl9mRVo7U5mp99rsBBIQ1MrmvDA2Tp4jQA9A==,iv:vmsOMW3FJck3CLIfewI1wITcoMqIL5IAWwEdHQPpQNY=,tag:GPDtdBmiF3/Ct8SS3FPAcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5emtRc01FdUxkNVdFMnp5
            MmJ6b01SWDdZd0h0bytwZks0MHEwNXRuQlc4CmhMK1J3Q3N2YnJtRHB5blZBczhK
            YW9wQ0RVQ0NoQ2NhLzhPbEF2Qm9NUUUKLS0tIFV3N1F3djhoVVZFRUtwN0dNRjUw
            VVEyNS9uVUpndllIQ0xHbzFDUzlmV1EKvRqbgdBktn/0w/0c0ObDEFTL6IGl3Cxa
            bNO9tikJyxvPMafQ/Y0ChDGGmfimKgy//Ox8OjsL7Zg9pb0JMPth4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T17:29:36Z"
    mac: ENC[AES256_GCM,data:7cLshRoRE91MtFCO3Ia8tGNfGWTH+hbZ0+S+Qvr+brD5zb1GfHHgCFV17eISryFti5iVMoIhaJgI9sAA5WFBzk44vmU9RbHmKD1HDRiq97frslotTA1hELzxtIU7d4Y283ArX7HxuKnvAriT0gpnDwOr7vzylNlUxVOEZliwJik=,iv:/QlJ3AbU2hl5OwNM75tuuLg8tMMIgF8TF/tOBzUYmKk=,tag:Ev8yYh3KVKJ+4j3rZUaaYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
