---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.x.x
  interval: 1m0s
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: apiKey
    nodeSelector:
      kubernetes.io/arch: arm64
    policy: sync
    provider:
      name: cloudflare
    sources:
      - gateway-httproute
      - gateway-grpcroute
      - gateway-tlsroute
      # - gateway-tcproute
      # - gateway-udproute
