---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
