---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: risingwave
spec:
  instances: 3
  description: "RisingWave DB"
  # affinity:
  #   nodeSelector:
  #     kubernetes.io/arch: arm64
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 10Gi
