---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-benwoodward-cloud
spec:
  secretName: cloudflare-benwoodward-cloud-tls
  dnsNames:
    - "benwoodward.cloud"
    - "*.benwoodward.cloud"
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer
