---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-v2
resources:
  - cloudflare-certificate.yaml
  - cloudflare-issuer.yaml
  - cloudflare-secret.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
