apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 33.x
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 60m
  values:
    tlsStore:
      default:
        defaultCertificate:
          secretName: cloudflare-benwoodward-cloud-tls
