apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik/traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik/traefik
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 60m
