---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.10.1
  interval: 1m0s
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
  values:
    // TODO: remove when new version releases
    image:
      manager:
        tag: v1.10.1-hotfix-2
    upgradeVersionCheck: false
