apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-no-replicate
parameters:
  dataEngine: v1
  dataLocality: strict-local
  disableRevisionCounter: "true"
  fsType: ext4
  numberOfReplicas: "0"
provisioner: driver.longhorn.io
