apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-no-replicate
allowVolumeExpansion: true
parameters:
  dataEngine: v1
  dataLocality: best-effort # means that it can move pods if needed
  disableRevisionCounter: "true"
  fsType: ext4
  numberOfReplicas: "1"
provisioner: driver.longhorn.io
