apiVersion: v1
kind: Secret
metadata:
    name: grafanacloud-configuration
    namespace: alloy
type: Opaque
stringData:
    loki_url: ENC[AES256_GCM,data:Ez720Om8LciRRKlPdiQ5cq8+JNd0WbV2nmT2+bJKzSnvVsztxJaf3z0ElA4ttC/YOBI=,iv:xaxK3/YAqXGVvF8XCVjKHjzXR271RWmVJAiwJDXxX7Y=,tag:I9EQNgygnIEC7Z+4F98fkg==,type:str]
    loki_username: ENC[AES256_GCM,data:dHWRDwyaDw==,iv:w4JBDHHIqLaHlzvPd9vcPpcLSnJhKs9J0jOq1LZ4K3Y=,tag:8J66Ka9lVMB6dFp122kThw==,type:str]
    loki_password: ENC[AES256_GCM,data:27nCS3DWjz5PjktMKWualERwbALS0CJeUImg+3DwJu0Xem1fa7vPV4vNm7Umfletm4KN5BaDQjUGHu0jDHELmeUXylCeyK5auZyy/jNUjnEIU7SOSwOwM4xW3KkWSqMGax1LHZVRT20nqLAJYM4fgn28dK3WR9U6ccCRYUEYbEcbjd+Pq/YFIHOC6quDJUVxt1AzXcvVEoE=,iv:BXA+UciNaPSgZ0T8VQapkiRbzGZ/SQ0ZTtF5yPmM2wU=,tag:YJl+13H9NqaLUilpwmI+Ow==,type:str]
    otel_endpoint: ENC[AES256_GCM,data:vbZY86vQqaxMkjPhUeO1b56YX3xTWOdx3CuCahV03dvrJ3IFKGJ6F19IBYuL,iv:+Kng9QnNhoPpflbkc1na9KT2xfDQ8DMpOGHOj9uOFKA=,tag:SJaKBaGibU2Gj110eLPGyw==,type:str]
    otel_username: ENC[AES256_GCM,data:6mZn9TLsjQ==,iv:xgZM0S/Hm4ylYwH28FsQ9fEEvMNx/JDhq61XnRJ218k=,tag:R91XBjjwgXy7gxLBs2Sj+w==,type:str]
    otel_password: ENC[AES256_GCM,data:bUn2C1ywWooy24Nihl/WNbCl0mBgAKJuGknZPwq6wh6ql2G976P02E83OQEX7ZT8tvcpKIlrgGJDPLRlB3XV0CibYQ8ZmeuXD68fAwPG89JWQvJVCmWHgn621Sy2hITnkyc98Ko5VmYFXqd69gCOPB9faDqZz8LkuSkhpPIMEQG0HvsnzKt7a1djmExxN2c6/gcqlLFBRss=,iv:M5Hvk0zlW9Evm5RsJaPKXNolfumPBmchceAdsYWpIFg=,tag:yF3QlLuq+MAmZSsjziA72Q==,type:str]
    prometheus_url: ENC[AES256_GCM,data:PRG5KOWWGwbeon5uuJwOywAvs9ILG8LfoW7K5TyxI1u6gLTF4b1vZKA5hzlUtcO29a5wr4xkg5ILt7cubz15ZqetV1o=,iv:aVKCi4F9gRWd1xQAOmS/f9x81EaU6TiygD7JebZk5E8=,tag:cMDDzdidjGLxdo9m0diz1Q==,type:str]
    prometheus_username: ENC[AES256_GCM,data:TmZyYimw0g==,iv:8sfoXBEelJmQDaYoNcuvV/PS+2AUUcRD18RriJzDMDU=,tag:NQgAXhzFNGJfexLvEp2n8Q==,type:str]
    prometheus_password: ENC[AES256_GCM,data:tGqXgQRO2QCrOIyVtv581U7Fn4JnxkE76L6hMwaKL2mw5ZEFhcJ9vbreXUXcS/3Qd86E1um0TXJjdpGfOMbk1K32i0NTFOyiIeDVGKIG4m2D8L20x8Y6U8FTJV906OwsDWpFuTNXfkZdRZAvR4C93BgEhwBXVc/4irf66IIrfsmzisjLYh3LjM+JHhfj2gCj8bF1xCG4iv0=,iv:qmsiplnWBcrRdtRI3o2bxv22HIw9Mvpf1Q8VSvYdxnA=,tag:GvXBsxSBJvHtQ2KOh5IG8w==,type:str]
sops:
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMUFwQW9CUlBzUXlwN3BW
            RFN6RzlaSWhOaGJjSFRjNmdUMDZkTlNnWTB3Cm9WRWhsdXR4RXhIcUlWdnU2Tkdy
            QU1tZGFudDZiVlh1MGNRbzhWQllTblkKLS0tIFFoRFR4NURYakJzeEk5aStaQ3o3
            U2d4cVI4a3VUM0ZEdVRMeE9mVSttT0EK/6JilDiP8VEOKB6J5xbGczMZ83NoEmuq
            /1kyVorQV40B8ssX69TviS/xgKHAkZ2ci5CReOghMWcCJ1o1xDjUmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T17:38:45Z"
    mac: ENC[AES256_GCM,data:4Q42fWzgZ6IFz+T+F8XjbatWRM4p4shQMzniDLhAL23HvCsMoUcMKCzTErggOLjwtV7f1r3S7pyInh3u2w0nZWEcU0sTE64DYydgTeaACaT9XsOYIUs3FcMOT3tdM9BBoXs+cMwUBXsOoJsePBmWc1+m+DUZMgn6DOHAK9A04aE=,iv:sRTz2O4f8caBscHsjG7m7AFA2Fcfb3yAGXipKJMg5zw=,tag:ObjU7bk3Y5G5kpmxnxqFBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
