---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-cluster
  namespace: media
spec:
  instances: 3
  description: "Romm DB"
  affinity:
    nodeSelector:
      kubernetes.io/arch: arm64
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 10Gi
