---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-cluster
  namespace: media
spec:
  instances: 3
  description: "Romm DB"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - arm64
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 10Gi
