apiVersion: v1
kind: Secret
metadata:
    name: romm-api-tokens-secret
type: Opaque
stringData:
    screenscraper-user: ENC[AES256_GCM,data:n5nCbwQ=,iv:tEpvpJI7n4rMJqlvh9DBiJqPDu+IZvYmJK2aLZlyCK8=,tag:67JBdFdc02X/t/2JJyhZdw==,type:str]
    screenscraper-password: ENC[AES256_GCM,data:PCak+gJLiGEw4belRBlEH37C0MM=,iv:Z3643wGatmL22APzU+S8R1OKNgxbrhEjB9oH4aWDhBg=,tag:Isb/ig+5dX5224izw68/wg==,type:str]
    steamgriddb-api-key: ENC[AES256_GCM,data:YCN3R4Kv6xJct1m8K8x3ScuBt4TsXGl/E0+cLpfuTSE=,iv:smLjlp50pbUQdToWNz9Sb8TUVgxT4KTePpV9qxvkNs0=,tag:13Ii1aCO/KYwLSpquK13kQ==,type:str]
sops:
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaSt6TElHb3V4VWRBVk9x
            UGdBRFYzMVZwRXRFUXdnampxZzRFVlBhVURFCi91MllEcFh1eTR0WWVtVHBFTTZT
            aHVoQ1ZhSVQrT0NJcWRET2NWMm9DQUUKLS0tIDdGSFByRHlMVENZMFFuOXplcHdr
            bndld3NpZ0M4KzJkYVg1Y2kxUGs2eDAKP/9wQ6p0B+CqpGn7juaorCevJZon7DSF
            I7brrsh6PI8+9Aw07cX4m+5POOj7gSvCF+6QEwvuIVENFHT5UdLr8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T16:43:04Z"
    mac: ENC[AES256_GCM,data:pFuazLyI1OjG8ZVkkVA4rVXG6DePbkwMpTfWuYB8dKLn2RVzRD6LA9OPwmTBtLM6wMHzS586DOS+nfhQzkrqDpoIVCuesuLat7tspA2KwApvEMdlG3pezBlRkc2QXo+RnLd3GRYTRxUt+m5YYbpA6Ok2DP2Qx8a7d1OgAl8lnlo=,iv:LM86jz1Ig283kSVTyLXjE+w9ZV5UTfTJjYAcrI7RtVQ=,tag:Uq3pdloRhkfHErWM0OkQSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
