---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
  namespace: penpot
spec:
  chart:
    spec:
      chart: penpot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: penpot
      version: 0.x.x
  interval: 1m0s
  # https://github.com/penpot/penpot-helm/blob/develop/charts/penpot/values.yaml
  values:
    config:
      postgresql:
        existingSecret: pg-cluster-app
        secretKeys:
          postgresqlUriKey: uri
      publicUri: "https://penpot.benwoodward.cloud"
