---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pl
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: pixie-config
  - files:
    - pixie-config-values.yaml
configurations:
  - kustomizeconfig.yaml
