---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: kube-system
spec:
  chart:
    spec:
      chart: forgejo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: forgejo
      version: 15.x.x
  interval: 1m0s
  # https://code.forgejo.org/forgejo-helm/forgejo-helm/src/branch/main/values.yaml
  values: {}
