---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: default
spec:
  chart:
    spec:
      chart: sabnzbd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sabnzbd
      version: 22.x.x
  interval: 1m0s
  values: {}
