---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
      version: 0.x.x
  interval: 1m0s
  # https://kubernetes-sigs.github.io/node-feature-discovery/v0.18/deployment/helm.html#configuration
  values: {}
