---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: k8s-at-home
spec:
  chart:
    spec:
      chart: sabnzbd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      version: v9.x.x
  interval: 1m0s
