apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  chart:
    spec:
      chart: dapr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dapr
      version: v1.16.x
  interval: 1m0s
  values:
    global:
      nodeSelector:
        kubernetes.io/arch: arm64
