---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - authentik-values.yaml
  - database.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
configMapGenerator:
  - name: authentik-config
    files:
      - config.yaml
configurations:
  - kustomizeconfig.yaml
