---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - database.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - secret.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
