apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:KIXR0rPVRkLj9DJ4wsWpjPh8vSJpAj5rIg3c01zulkFt3AUtgT5lcx7HPSwMm/5pOIJqZgVS4L4uJBeOJnmygE8WeMknyAAPtqLoXDEGlhU1PId3XkSyfL6A5VCvroMICI4c4eN7woYKt50F9wMWwbHbhTJk43ta/kDdkR/vXm8=,iv:BcNBqHYg9lfqEJrNeWSGuC7Dqh7jbFb3881B99kaa7c=,tag:q+baBNRVxnkQFhKYfXuXeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTWdjTW1xcnRYSkxSUXBC
            WkdEVmVkKzZhZnAyTU14QVBHVk13dFl4VEcwCjlveXkwME9JZE5KRnNFVHBPcjYr
            YlJMZU5CZTdqZTFKMURPZGFFRXk5TWcKLS0tIHZhWEJDK0UxVGlITm5TMUVVc2Y5
            Sk1yYllCNVpQN2FJUWgxV2Fndk5XRE0K96rIfvFUnzRFHFr2xp5896kinBc6ucME
            VD/10+nFMAdocHsEFPxUjOZbbAz8cpN4MD4MWIbxDKmVX24P/ukVpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T15:59:19Z"
    mac: ENC[AES256_GCM,data:Jl2JWYsnonsmmoTDf2VutBjL5Ua9dlubstHEDWORixD31tAHKhlBuwAvyI4U0ARbLMyKKKPM8+S9FqyC1Zad5rX20Etabyj9UMHj2BMwmSOGhflEzLlBVTjvrQB+GdTHTsYasGpM5zSkktUmB3OTvzxKRezf3vdzds+dYHXXoqo=,iv:Bs757o43XxzMew+tEelAb9m6wt6frdBtKsI911dkO8E=,tag:8mv/L2PytRfCaSUzjDgZFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
