authentik:
    error_reporting:
        enabled: false
    postgresql:
        host: file:///postgres-creds/host
        name: file:///postgres-creds/dbname
        password: file:///postgres-creds/password
        port: file:///postgres-creds/port
        user: file:///postgres-creds/username
    redis:
        enabled: true
    secret_key: file:///secrets/secret-key
global:
    volumes:
        - name: secrets
          secret:
            secretName: authentik-secrets
        - name: postgres-creds
          secret:
            secretName: pg-cluster-app
    volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: secrets
          mountPath: /secrets
          readOnly: true
prometheus:
    rules:
        enabled: true
server:
    ingress:
        enabled: true
        tls:
            - hosts:
                - auth.benwoodward.cloud
    metrics:
        serviceMonitor:
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL2lHUXhnZE1VWFZ1bVJT
            TzQvdm1LakUyQkp4NzZWRDA3YTNmaXcxK1gwClZHdlk2ZW1RK0dicFlINkxkZVhW
            bXpGdkxEUVdtYmp0c3lBRzlFU0ErZ1kKLS0tIHp4bmFidmRIZmdkU0lrRk90enor
            YXZmWkpFaUQwZjVrYlU3V3psQXQ5c1EKIzfHmj1lN9DudRrVIZqnZcrQLglgmmUy
            PqCsKU1+OvkjgLrEB+xvK0tgYrDtvtjgVRoq19UzGLRNoFJbmGcdBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T15:56:50Z"
    mac: ENC[AES256_GCM,data:dKFrf/E00fd/5TRoh29esP1CBGOX03yMV18vOEXxZ6EEpKuQx2Tb4ub0HGtKaKB4lwoymArzeVdMTcvOkFXGEMVAuwEtFeFMN9R/CrL3KNO6MfIejAkS/kl3sMshiJBZt2Qpt/LNZw7rkvAufzi9X2x4H6iPm6RLBgmNH5b+zts=,iv:uEl3Nzx+A4p9YaCuQtVrllxh/CCZUV1b4E/EI0q7iLU=,tag:Zdy3dLl5MfTvCyEvQNj0lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
