authentik:
    error_reporting:
        enabled: false
    postgresql:
        host: file:///postgres-creds/host
        name: file:///postgres-creds/dbname
        password: file:///postgres-creds/password
        port: file:///postgres-creds/port
        user: file:///postgres-creds/username
    secret_key: df1d6122db4497759461961806878995292d8c4d213fd6a26b45366026185dad5410ede2522a156767bec25a5883e7f13f8c41252a899243b0e24e1fb6737128
server:
    volumes:
        - name: postgres-creds
          secret:
            secretName: pg-cluster-app
    volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
worker:
    volumes:
        - name: postgres-creds
          secret:
            secretName: pg-cluster-app
    volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2RGejZ1L2JJWDM2UEF6
            Y0hTc3FraVByM2I1UFRiakdjNlFDYlZRSFVZCkFCZ3pDdEFMM1piOGYzNURTUnhz
            TWNXQWtqZmQrNlBGVHVxSlVJOVJVbWcKLS0tIFZOUHlLNVFkLzVtOTFTYjc5RUpV
            VE15cStQK09oV0xZNzlqaEpRVGh5dlkKwAENzoNtXoL2F5hmk9r2VDtoKanDXVge
            cKJhaqi4WSrmTnX0PjUdNxZUQ9wSGnS9Dl1AxcLlWas7WfT1JXqK4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T15:42:08Z"
    mac: ENC[AES256_GCM,data:sIthtNIuwuhH4owzp4QuNZREsdACZAqmKin+Nn7DtZeeiJdo5bhm4/jOKUyDoE/zQjpNEmKICCLV2UYpbI7eEp31Qt87tj8H5OHUdfAAz/aV4mRnXXclGbCKGVtFTuybmR7JaecdsxR0y+ATzOGJzGPcr6MhT6ATHASScD/nsrI=,iv:hFYWGBeX+0oqpsyrjFBUqnkE2TbbLkx3M1+hAAsnDac=,tag:Hgq8mVOvTHz0mRaYOFoJiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
