authentik:
    error_reporting:
        enabled: false
    postgresql:
        host: file:///postgres-creds/host
        name: file:///postgres-creds/dbname
        password: file:///postgres-creds/password
        port: file:///postgres-creds/port
        user: file:///postgres-creds/username
    redis:
        enabled: true
    secret_key: file:///secrets/secret-key
global:
    volumes:
        - name: secrets
          secret:
            secretName: authentik-secrets
        - name: postgres-creds
          secret:
            secretName: pg-cluster-app
    volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: secrets
          mountPath: /secrets
          readOnly: true
prometheus:
    rules:
        enabled: true
server:
    ingress:
        enabled: true
        tls:
            - hosts:
                - auth.benwoodward.cloud
    metrics:
        serviceMonitor:
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZDdvUDlZSFNIZUd4NmZp
            eGhPT0pjQmNYOEh4RTZqY1dJek5pd3pFd1VnCk1xd1RncUJIY0xlUUZWaTd3VmJI
            WC9QbWM2WUVOWUd0OUNyYXorcWtmUEkKLS0tIFFieGo2dUswWWhQbG11cDhPZ2ty
            SHlKQjVNSWFSYXg4ak0vUEZ0TVFkbXMKSXAaW/GYslrgCBjL48TLg3X0AvtTZULM
            FO0QH7/t8ot1J4E9h8hAWi/UbJd9FdLC9zbuAQ0cueZ/LLA47T3xiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T15:57:22Z"
    mac: ENC[AES256_GCM,data:Kbgn4sWXQ6dpBHQCpjvBSlCf6HEUPpzc3V1FMlCOkLpc++5YhPK1QZFk8PDDbFuIO2Mk2W9SE3rIjASRuKYNyS36avP0z+gRoA9bTXUWm7mL4heGdMUojYjpzyQkiAzGFiOUt4mQ8kXuwSu3tVkOYozuHl5q0CXE+L0tgFdDgWw=,iv:X7YFC1xijC7urZRGLNFyg23/kGm3prql+EQXdnzHE58=,tag:CMMea9HV5yYF3BmjPBPhRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
