apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: calibre
  namespace: media
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - calibre.benwoodward.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: calibre
          port: 8084
