---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: akri
  namespace: akri
spec:
  interval: 30m
  chart:
    spec:
      chart: akri
      version: "0.13.x"
      sourceRef:
        kind: HelmRepository
        name: akri-helm-charts
        namespace: akri
      interval: 12h
  values:
    udev:
      configuration:
        enabled: true
        discoveryDetails:
          groupRecursive: true
          udevRules:
          - SUBSYSTEMS=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838"
          - SUBSYSTEMS=="usb", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60"
      discovery:
        enabled: true

    webhookConfiguration:
      enabled: false
