---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: redpanda-operator
spec:
  chart:
    spec:
      chart: operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redpanda-operator
      version: 25.3.1
  interval: 1m0s
  # https://docs.redpanda.com/current/reference/k-redpanda-helm-spec/
  values:
    crds:
      enabled: true
    monitoring:
      enabled: true
    nodeSelector:
      kubernetes.io/arch: arm64
