---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: redpanda-operator
spec:
  chart:
    spec:
      chart: operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redpanda-operator
      version: v25.2.1-beta1
  interval: 1m0s
  #
  values:
    crds:
      enabled: true
    monitoring:
      enabled: true
