---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nats
spec:
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nats
      version: 1.x.x
  interval: 1m0s
  values:
    config:
      cluster:
        enabled: true
        name: nats-cluster
        replicas: 3
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: 10Gi

    podTemplate:
      topologySpreadConstraints:
        kubernetes.io/hostname:
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
