apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stash
  namespace: media
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - stash.benwoodward.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: stash
          port: 9999
