---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 7.x.x
  interval: 1m0s
  # https://github.com/minio/operator/blob/master/helm/tenant/values.yaml
  values:
    tenant:
      name: minio
      pools:
        - name: pool-0
          nodeSelector:
            kubernetes.io/arch: arm64
          servers: 3
          storageClassName: longhorn-no-replicate
