apiVersion: v1
kind: Secret
namespace: kubedb
metadata:
    name: kubedb-global-license
type: Opaque
stringData:
    key.txt: ENC[AES256_GCM,data:AmHGUCwEZNTOdrAe+oUjLGjnvy+zjIcTTrQYKwQ5DYnxV8QoIPVFuW6bY3iLjfDoDQB1ULL1EzS8AltPlHAPlwfclvJHjdLSnw51dd8RF9TG3pPZtlgrdYoFu35xE8USeYq57auamunH7s/vUm9hhw4rzAZFOx2gn87Cy5+k3oO4Tj/auIZlSNgpeD4KYDUj6Y0mS3vT6u/DKSuV8SBP4UH/j1OaTCkTN3anZPftBcaLW1123Sk9bzih6uzaDathADfT70KXTmZruWLvtvmXFmjWnHArozrMVamtjPMP7ePDUZdoDCHdbLJ92ivhRwnePKbGOsEx3pNi/kuIbZupW8Rccdy27bz2YllLjgfQRs0aSkjETRhuLs78b8Jk6mh5yFnmO0fW0tk/LRMqJzP7udqJncrywAhWzp9ILc6its7OByrE+q0CKlF0Y+VWxR1/drvX1KuKkFxx1wqMp2l5fMjmWGZt6Gudy0pPhGolX6TEOkVMBAH9VLKjXixtmeHbrk7IKKXKiCZtlwizgFZ+HPKPcN9WmD8frygOyn/5ZSIfEedmYO6oqe75Bm12wB9a2R8JVRtrgWkvVK9aFSVnSWQ7K/K0YZvE74yEurLVaSb9HR3/MSr3yJY+DKx6YRhjR2REp/QhkvjWI5t2XsVihnWy/sDdfELQwy2mcDRK0ue9H+lTVU3ckZQaKEDg0hswF6qtzE0Jv/eow1KOw44GZfAI8rRyZ6laHQArqedUeYeWEIjDfNDr4+us4OOvJSycq9fkx5KmCHSx9sk6fv/8RV+Y2fllgkvj5UHGgUfEpH+Hi8U6sL/JIm3JOWKq3VVfcig2jfdPwm9k96dX6Y4mCORI/8YkI0aRYRtvCSraot2K6aH710mP3BehbYbbrb2OpdWOM1wb50XDgTqa+SX0uoaSFYP5zyVMWl/J6ql99t8fcIcTpFBDAeUxpvROPak39EerF+G7ua38zeaTgngpnrstE13RfaOGDKeVBsIpmjZbfEfpHZKzIdjTAFFeRv742QPONif6/OH463vK/WrEG5gtnWIY20KZfpAeg7BrySdjUiF7Qahps+TYyQjZW3YVn1rWlgE6L3gqcbrrRG2N6Qgh/6C1X65K3UE3gjl71iS3Z2gvUuNRQKLK6WH9byYvHBytNqph9QQkhuRLsbpZbkuV7SaF9OuAfbgJtQVtC9vybYK3yf9EhZlSxOkTCd+0CbJeZYw0cHczKNHk6lrQFy8w9TPiBHaPnocvmhGo8aA95TYgRLGU4t65oZLoYTynjXR3F2YQpaQdLiuxP/rQrbfj2ebE8K3/kobCe0C7TSKQ2jck0q4XMc9eDhx6gMG5If59ojhTwrl72/eeeszp1iMjEhYgRZppfSBR2NDtsdWWbDmjU4HuDlURUicO9Q6lv1twr3UXxNh0u3Fbxnol7lMe9uwJu/77HAVrgE02O7bdzPTIjXdzs8IDg8HfsMzQeUNYT5U+38vdaZRrlOQGVlAXoSyPZHkOI9BEV/27E6thlhgu+w+P1138dhVgmMuTCSQ9d5JjDXXTPLTHfFv1P0BEqTniXHG3jnB3nLEeRUHg/pH1aFBfSn+bXSC0orH4ZqnBYQC6ClvTLZKh6UT193U1tWkYORnfc5eoZrrH2U8k6/ftoSN1yYeuTdT/JGzc5FhPcXzGwV0Ghh5P+Bw7Ehb0L41XShc7UYFtjEp7OgNxbr6EeNNxkzn+0J04UxZZjqZdXycBcJbrBDz52ZfDfqC1tpAocsLxuvP/aEY0M98kdr3DM/FmJCA8GuZNCq+gDC1+pQzO8gwE3ezxZHeeNdw+M0gWR9l6e4LRoLZxxky7uh/aCStfSv7CR76T7ll6+WS5E+0FO+CZbP/sQlLyJWiwFkMTFidThl8FDyzGTCGhIuqUbDhihJw7ZA/ZM2tzWGI3CDafI5d8VKOKYOlfcIR12TXef+v34AmfYUlVQiZnxi1bbi8DAG0dcOXXt1waWiywdVI2aHcOrPWe0y2Hz9kNhfvosYAECIGBxY8uEUF1JEMybf/lArT3yYD3uCcM2QRfF+Mq1/7MUSueL5K1/puqQthwC+BeGruNwq0=,iv:b1fR99NyoibuPP0JHEj8q74b2/mrq5dpPGeTrd+sJ4M=,tag:0TyrLRjoLrY+tZY46Xk0ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb3BFOUtxRGRWcWRLOHdt
            SnlINmZxeU1ZNmVnWjR0dHlqVHQ3c3dlcFdvCnhPVkRXQ2tSTEljZHpGU0lLSnhv
            STdTQ3FDdmJDb2Q0WmxSaWd2QmFscFUKLS0tIFpPWGVSR2F1Y3NLdWlmcG05dVNI
            N0ZVeVY0ZXE1dTgwSzJuWnlaMk5TTzQKY+kMDzr+ukv9XavVvOfqInd8lU8NOCRP
            O5Zdj3cHLih6tLWkEKwlmkfTtjcsgy9Pg9oDHWinqQgvxGuXnXZ62A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-22T20:59:35Z"
    mac: ENC[AES256_GCM,data:2C24S1HbfYM0i80wxoqQiy0UI5kulbowL4BmZJEBbNRD2DzAHoGLRoRZxVoKxFzfiQDRkZ8usTZ5FHXWY4iZrFiQ3XNSVrAZ1207QlTZUdraaR/R6Dbs3aQCX/BkTNlzVjSgwM0xviqPKp4zbCszzAGr5FhODO6nfsCApX6QjKk=,iv:xzDj81N36SuN02vjWiQUyInaQ3Jx3f5sQkXsd8hBwsE=,tag:qkjZ6RgLJQOibXjLcxyAoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
