---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubedb
resources:
  - namespace.yaml
  - release.yaml
secretGenerator:
  - name: kubedb-global-license
    files:
      - key.txt=license.enc.txt
configurations:
  - kustomizeconfig.yaml
