---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubedb
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kubedb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kube-system
      version: v2025.6.30
  interval: 1m0s
  values:
    global:
      licenseSecretName: kubedb-global-license
