apiVersion: v1
data:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:QlGGUVMkaVH/QkKw7rs4nRbv+pNMVlkwoerDKTsVbzfYyMraO44AmlUPI38=,iv:Nrr+JOhdWd5hUOj/bvFszjjZgA7Mr7NRgKt8CtQWva0=,tag:neeSFgVKcBK72w/ZxbB4qw==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:MdKnpB5Oykl4T9C2+SGKqQn225AQR3b4KE34DbjTSLDy4c0lxPeRq8ckWNc=,iv:7GEtSrKIj66RZkdtK1Ykkll7fZ7LprvbzkTMj3d//sc=,tag:PqSM2IT3W7YNYyBfo5UTiQ==,type:str]
kind: Secret
metadata:
    name: storage-user
    namespace: minio-tenant
type: Opaque
sops:
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTUlqRi9DTXIzM3pZOUdi
            M1pnbC8xYVVHczRqdGZTdjVSQ1NZQUV1SlU4Cnh0b0I4RkpxRFQ0MVdhUVZDUXBl
            Z3dtSlVjTGNHOW43WWpxbThTdmF2bzgKLS0tIHg3RkRiVlRweHkwNDkrMXloT0M4
            RXhlWGpwSE1RTWc0dmVvNy9zQmJpTXcKLCyvLvpHzZMKu/jSP9ZT47tZLD0EAat0
            fNaJ96JHR8YTToiUI1Wi4BtDDsYI3aiGB+Ju5pIXBoYzFRgJq8AzJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-25T15:05:04Z"
    mac: ENC[AES256_GCM,data:EKPBc8nhVxW39kohsCA73rvtryfLP8B7gSWITM5QmVroATkh+1V71x04Xy9g8nbiz03EP3as3cd2EnxoVO+4zCwzWtQlQaZqr/G5cyX+EGxmeu1nEP88yT+UTWsE1xtfudIjq5I9JQ8gHnA6JAuSVuRZEU/a653W6dKc78bpoUw=,iv:JNdnM8abfPiaS9o1jBO3wvfw2lMQM/bZ6MshAOofC9M=,tag:jWv3SxCAif3n//6iDjH/MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
