apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: noe
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/noe
      sourceRef:
        kind: GitRepository
        name: noe
      interval: 60m

  values:
    dockerConfigPathCandidates: []
    image:
      tag: 92a3f70dd443e1662648cf77e56fc6d4f789dedf # TODO: check for latest
