apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: noe
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/noe
      sourceRef:
        kind: GitRepository
        name: noe
      interval: 60m
