apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1m0s
  chart:
    spec:
      chart: tailscale-operator
      version: v1.x.x
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  values:
    apiServerProxyConfig.mode: true
