---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  chart:
    spec:
      chart: spegel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spegel
      version: v0.0.30
  interval: 1m0s
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
