---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  chart:
    spec:
      chart: spegel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spegel
      version: 0.0.x
  interval: 1m0s
