---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: inteldeviceplugins-system
spec:
  chart:
    spec:
      chart: intel-device-plugins-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: intel
      version: 0.x.x
  interval: 1m0s
  #
  values: {}
