---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
spec:
  chart:
    spec:
      chart: mimir-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mimir
      version: 5.x.x
  interval: 1m0s
  # https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml
  values: {}
