---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spin-operator
  namespace: spin
spec:
  chart:
    spec:
      chart: spin-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spinkube
      version: 0.4.0
  interval: 1m0s
