apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: rook-release
      interval: 60m
