apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:R7BqNQX7GjKvPDbMmM1nYY1tGiuGbs7A3+kMQiLp3qor9kTZI3C3gQ==,iv:IdzVleqAMlqeGFWTBJJFHKi3YOVgsc7mOf/R52jfsLQ=,tag:gLV5jynojLqK4vGdmM9QbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQldJQXRtSTJqbGd6Q0w5
            b0RUWjcwWjNVWUdEQnZFZG1SUjg5R1hKRkgwCmQzRVA1YWxLVGd2YUNrbzJuY2I3
            MUwwaDlNenNoNWh4cW5sK2FCTVB0azQKLS0tIFB2ZDFibnUvRFlud1BlckFKSWVK
            TU5ZdnUwTWNNM0tWNEdWb0toSy9ONnMKPtvN5fyfZ2lOawoo8rerMrhqhwcX7ihP
            7d0jWUkTbFENoVs0oR+yXuXhs3l9XGIa6dLCc2i/i63JIfJK4t6/Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T18:11:28Z"
    mac: ENC[AES256_GCM,data:7oF9cnahIchdsv6Iv+ioZjucIRErIPaXwPsiggN5frvzDM8RvRehz4RkNNCDtBZaJ6wOx1Tw9mGXzk0dv7L7lL7EAFm1Q+Wj7QjbvLzY4p321av7zy/EEP6potIw6NNJXuxJuPwfGwVZQGSrFvd0+INXFdAvCjGpWgj3NGUi7uI=,iv:EqeMPZ+xExcsoJZw2pYw/ht8JCS9QePNCfIZf11zpm4=,tag:7xuU460TmkoRPRYoUbR5+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
