apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  annotations:
    cert-manager.io/issuer: cloudflare-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.benwoodward.cloud"
      tls:
        certificateRefs:
          - kind: Secret
            name: cloudflare-benwoodward-cloud-tls
      allowedRoutes:
        namespaces:
          from: All
