---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homarr
  namespace: media
spec:
  chart:
    spec:
      chart: homarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: homarr
      version: 14.x.x
  interval: 1m0s
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/homarr/values.yaml
  # https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
  values:
    persistence:
      config:
        size: 1Gi
      data:
        enabled: true
        type: nfs
        server: 192.168.5.250
        path: /volume1/NFS
        mountPath: /nfs
      icons:
        size: 1Gi
    podOptions:
      affinity:
        podAffinity: false
      nodeSelector:
        kubernetes.io/arch: arm64
