---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  chart:
    spec:
      chart: coredns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
      version: 1.x.x
  interval: 1m0s
  # https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml
  values:
    isClusterService: true
    k8sAppLabelOverride: "kube-dns"
    serviceType: ClusterIP
    service:
      clusterIP: 10.96.0.10

    servers:
      - zones:
          - zone: .
        port: 53
        # -- expose the service on a different port
        # servicePort: 5353
        # If serviceType is nodePort you can specify nodePort here
        # nodePort: 30053
        # hostPort: 53
        plugins:
          - name: errors

          # Serves a /health endpoint on :8080, required for livenessProbe
          - name: health
            configBlock: |-
              lameduck 5s

          # Serves a /ready endpoint on :8181, required for readinessProbe
          - name: ready

          - name: log
            parameters: .
            configBlock: |-
              class error

          # Serves a /metrics endpoint on :9153, required for serviceMonitor
          - name: prometheus
            parameters: :9153

          # Required to query kubernetes API for data
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30

          - name: rewrite
            parameters: stop
            configBlock: |-
              name suffix .cluster.benwoodward.network .svc.cluster.local answer auto

          - name: forward
            parameters: . /etc/resolv.conf
            configBlock: |-
              max_concurrent 1000

          - name: cache
            parameters: 30
            configBlock: |-
              disable success cluster.local
              disable denial cluster.local

          - name: loop
          - name: reload
          - name: loadbalance
