---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: qbittorrent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
      version: 23.x.x
  interval: 1m0s
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/qbittorrent/values.yaml
  # https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
  values:
    persistence:
      config:
        size: 1Gi
      data:
        enabled: true
        type: nfs
        server: 192.168.5.250
        path: /volume1/NFS
        mountPath: /nfs
    podOptions:
      nodeSelector:
        kubernetes.io/arch: arm64
