---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 30m
  chart:
    spec:
      chart: temporal
      version: "0.67.x"
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: temporal
      interval: 12h
  values:
    # TODO: MOVE INTO OUR OWN SERVICES
    elasticsearch:
      enabled: true
    grafana:
      enabled: true
    prometheus:
      enabled: true
