---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-connect
  namespace: redpanda-connect
spec:
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redpanda-connect
      version: v3.x.x
  interval: 1m0s
  #
  values: {}
