apiVersion: v1
kind: Secret
namespace: kube-system
metadata:
    name: proxmox-cloud-controller-manager
type: Opaque
stringData: ENC[AES256_GCM,data:RrQoG6IlQfddQACVNrBPhMHj1QFY509Vc2yzDEbCgg/QyKNMwiJ/ccYiPTlcjMhk6HDB3MbNENy2ulSkZEW//NMnzuSSvy0b4EwwqDVS7F5ZLG7nJKu4Le6aumPGW3ZQYpKyCf7NJfasjMmXumIrTCVwm+XO5zZAUo5VqjUyF2AKk4dOKF3mzSVr8Dg34duz9vP4eLenVOi6u9Ar9hwcNwZh5qjD0jvmSZ7iIP3vN0n/CqNsvVKT2ZN2Qm85vaF6UpZAkNRD0bfC2HIevN0/iEebIuPzXaZxgkoB1FzOhA==,iv:hkgh2fGhYSzqr/ttKn2F4HEk07mJpJMw+MHTz57ysXA=,tag:iom2va5755XuhaPYrrhiXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGxXK3BZSW0rVmUxaHZu
            L2ROemFpOWZGbXhxZy9WMFBuZ2pwdlIxeGkwCnd4VnczdUR3NXpnK05nZnV3MEFH
            RHMxY3l5V2pwNDN2bEN3WVpxTnQ2cjQKLS0tIDExUXluSVh1enptbUVxdVd0ZGIx
            K0FzY0RMbmF5VENzTWhaVkYzQjRNY3cKjzzZTm7IbVuxo3E3U47lyA8pjO6eDEgF
            yVIl2BbKyibmBnTqRL5nG3TjQ43auSlFa1usZlbFDXadk8AIUL9OWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T11:48:55Z"
    mac: ENC[AES256_GCM,data:n7ru3yz+dfM6Q9bXIEuSowINReWOsdgzEVeU8U7GRUQ+Q8QNh5XIupCYDHJ+9XtnM1AAsNbETUiIqmjAGvHEBUdzzmENPx/vqv2Ss6xNsw1zzFvQwLS82POCKZVMvkWEUVXi74NjVmdSapafszZ8SYtmQ3MxzNfmgZK1840d+58=,iv:zz5W8/EW1Gaf2q4YsHNw9VxDWcCtenJ3Sh1OtVXvZ6A=,tag:cqxqHopUJa9xgfr5nzehAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
