---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: proxmox-cloud-controller-manager
  namespace: kube-system
spec:
  type: oci
  interval: 1m0s
  url: oci://ghcr.io/sergelogvinov/charts
