---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gadget
  namespace: gadget
spec:
  chart:
    spec:
      chart: gadget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gadget
      version: 0.x.x
  interval: 1m0s
  # https://artifacthub.io/packages/helm/gadget/gadget
  # values: {}
