apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:B/Y91jOW52L+U0aSCcDXmtVbMeaYwgDgEoQ4PBOnJx9MZetNSFaTjA==,iv:FbB9vOfDyP6H1r6CLwBMiBKdy4d6QEJrFgKUujovXtA=,tag:79IpWUsckJieWC5hQjmgQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15lvm85kem62em8d2w0n9ypg6845z7r9hktv2n6jeejg6am0l9ecsa74n5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOXdMNDEwanVsU3pmZDBp
            VnZwTVRTNERCb1Q5M2o2enoyQ3RMVHQvL0RvClM1L2RrS2RkcE53Y3RkcmRYMlAw
            YVB3THVISi9Xb1EwV1VIMmx1TTk2djAKLS0tIEJ2MHFBaXBlbS9EYXlhZWFBRUs4
            NkwxQnlKMG9taUpubWZROEtOVnNMdm8KFHeYzsJBtrB/+voj8KqdYDDCU1nOq/ym
            Bze4nK8hpm3QzxUcquW0MWdog6OkzlqeeG0aZuBfJ3lx9PTuUdu+Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-03T17:46:36Z"
    mac: ENC[AES256_GCM,data:2n/1W5GCBHjjrwD7RD14tVuDzosb3jgM7Pvz3uTg09fUYvzWfwrblj2HvFjw3+qbn0ulF8aAxWvles2kkRuLcoVfzs74d67z5CAnf3xxooX/WLMInNE2fZCj96lLeGfofDrCq8M6oDwCCZU2vSD2RpRed0I4hP14IzNb7wg+aI0=,iv:oddvhIBm4t7vZb1tdEVojrKphNOqEihz6+p2xX6JXfs=,tag:Ltbazb2HtvAWmaEyRz5S6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
