---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cloudflare-issuer.yaml
  - cloudflare-secret.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
