apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: benwoodward-cloud-tls
  namespace: kube-system

spec:
  secretName: benwoodward-cloud-tls
  commonName: "*.benwoodward.cloud"
  dnsNames:
    - "benwoodward.cloud"
    - "*.benwoodward.cloud"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
