---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 3
  description: "Harbor DB"
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn-no-replicate
    size: 25Gi
