apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-portal
  namespace: harbor
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - harbor.benwoodward.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: harbor-portal
          port: 80
