apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 60m
  values:
    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
        tag: v2.12.0
    database:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-db
          tag: v2.12.0
    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter
        tag: v2.11.0
    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
        tag: v2.12.0
    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
        tag: v2.12.0
    redis:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/redis-photon
          tag: v2.10.1
    registry:
      controller:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-registryctl
          tag: v2.10.1
      registry:
        image:
          repository: ghcr.io/octohelm/harbor/registry-photon
          tag: v2.10.1
    trivy:
      image:
        repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
        tag: v2.10.1
