apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 60m
  values:
    expose:
      type: ingress

      ingress:
        hosts:
          core: harbor.benwoodward.cloud
        className: "cilium"
        labels: {}

    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
        tag: v2.12.2
    database:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-db
          tag: v2.12.2
    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter
        tag: v2.12.2
    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
        tag: v2.12.2
    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
        tag: v2.12.2
    redis:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/redis-photon
          tag: v2.12.2
    registry:
      controller:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-registryctl
          tag: v2.12.2
      registry:
        image:
          repository: ghcr.io/octohelm/harbor/registry-photon
          tag: v2.12.2
    trivy:
      image:
        repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
        tag: v2.12.2
