apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.x.x
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 60m

  valuesFrom:
    - kind: Secret
      name: pg-cluster-app
      valuesKey: dbname
      targetPath: database.external.coreDatabase
    - kind: Secret
      name: pg-cluster-app
      valuesKey: host
      targetPath: database.external.host
    - kind: Secret
      name: pg-cluster-app
      valuesKey: password
      targetPath: database.external.password
    - kind: Secret
      name: pg-cluster-app
      valuesKey: port
      targetPath: database.external.port
    - kind: Secret
      name: pg-cluster-app
      valuesKey: username
      targetPath: database.external.username

  values:
    database:
      type: external # database credentials are done by valuesFrom above!

    expose:
      type: ClusterIP

      tls:
        enabled: false

    externalURL: https://harbor.benwoodward.cloud

    core:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-core
        tag: v2.13.0

    # database:
    #   internal:
    #     image:
    #       repository: ghcr.io/octohelm/harbor/harbor-db
    #       tag: v2.13.0

    exporter:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-exporter
        tag: v2.14.0

    jobservice:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-jobservice
        tag: v2.13.0

    nginx:
      image:
        repository: ghcr.io/octohelm/harbor/nginx-photon
        tag: v2.13.0

    portal:
      image:
        repository: ghcr.io/octohelm/harbor/harbor-portal
        tag: v2.13.0

    redis:
      internal:
        image:
          repository: ghcr.io/octohelm/harbor/redis-photon
          tag: v2.13.0

    registry:
      controller:
        image:
          repository: ghcr.io/octohelm/harbor/harbor-registryctl
          tag: v2.13.0
      registry:
        image:
          repository: ghcr.io/octohelm/harbor/registry-photon
          tag: v2.13.0

    trivy:
      image:
        repository: ghcr.io/octohelm/harbor/trivy-adapter-photon
        tag: v2.13.0
