---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: radarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: radarr
      version: 24.x.x
  interval: 1m0s
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/radarr/values.yaml
  # https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
  values:
    persistence:
      config:
        size: 1Gi
    podOptions:
      nodeSelector:
        kubernetes.io/arch: arm64
