---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: age-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./clusters/cluster.benwoodward.cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: age-secrets
