---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: lb-peering
spec:
  nodeSelector:
    matchLabels:
      bgp-policy: a
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: true
      neighbors:
        - peerAddress: 192.168.16.254/32
          peerASN: 65412
      podIPPoolSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
