---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: romm
  namespace: media
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/media/romm
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      namespace: flux-system
  dependsOn:
    - name: media-namespace
