---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  chart:
    spec:
      chart: overseerr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: overseerr
      version: 16.x.x
  interval: 1m0s
  # https://github.com/trueforge-org/truecharts/blob/master/charts/stable/overseerr/values.yaml
  # https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
  values:
    nodeSelector: {}
    persistence:
      config:
        size: 1Gi
