---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - release.yaml
  - repository.yaml
secretGenerator:
  - name: nfs-subdir-external-provisioner-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
