---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      version: 4.x
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: subdir-external-provisioner
      valuesKey: server
      targetPath: nfs.server
    - kind: Secret
      name: subdir-external-provisioner
      valuesKey: path
      targetPath: nfs.path
